audit_header: false
title: Technology Solutions for Property Professionals
description: Our mission at 4Property is to be your best resource for Dublin real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The 4Property, your professional Dublin Real Estate Agents.
show_custom_links_new_tab: false
custom_links:
  - title:
    url:
show_custom_links: true
custom_links:
  - title: Join iPPi
    url:
  - title: Events
    url:
  - title: Webinar
    url:
  - title: Free Consultation Call
    url: /consultation-call/
  - title: Monthly Newsletter
    url: /newsletter/

client:
  name: Kenneth Kelly
  title:
  license_number:
  about_markdown: |
    For 20 years, 4Property (formerly 4PM) has been providing technology solutions specifically for the property industry and currently deals with over 25% of the Estate & Letting Agent offices across Ireland. Over 200 offices with over 600 Individual Agents use Acquaint CRM on a daily basis with 4Property providing a full service of installation, migration of legacy data, training and support from our Dublin based office.

    4Property have also designed, developed & hosted hundreds of Estate Agent websites since 2000. In 2018, in response to change in user behaviour with the move to mobile, 4Property launched Design Bricks. This service utilizes specially in-house built templates that are super-light yet provide all the functionality of a modern property website.
  brand: 4Property
  brokerage:
  market: Dublin
  address: NovaUCD, Belfield Innovation Park, University College Dublin Dublin 4, Ireland
  phone: 00 353 1 497 7705
  phone_type:
  phone2:
  phone2_type:
  email: kenneth@4property.com
  url: https://www.4property.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.png
    CTA_title: "Property Appraisals, Valuations & Market Intelligence"
    CTA_text: "By matching & referencing house transactions on the Property Price register with any historical reference to these properties online iPPi brings a new level of understanding & context to the housing market in Ireland."
    CTA_link_text: "Learn More"
    CTA_url: https://www.4property.com/ippi/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Looking for a Dublin Home?"
#     CTA_text2: "Search the entire MLS for your Dublin home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/4PropertyIreland/
  linkedin_url: https://www.linkedin.com/company/4property/
  youtube_url:
  twitter_url: https://twitter.com/4PropertyIE
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Dublin Real Estate Podcast with Kenneth Kelly'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Dublin Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from 4Property - your professional Dublin Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Dublin, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kenneth Kelly'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Dublin Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg

site_colors:
  brand_color: '#f54042'
  theme_color: '#0c0d34'
  accent_color: '#e40c90'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#0c0d34'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#0c0d34'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
