audit_header: false
title: Better Property Valuation Minutes
description: >-
  Our mission at iPPi is to make the property market a more transparent
  environment for everyone.


  Bringing Property Professionals together.
show_custom_links_new_tab: false
custom_links:
  - title: Join iPPi
    url: 'https://ippi.4property.com/app/#/register'
  - title: Events
    url: /events/
  - title: Monthly Newsletter
    url: /newsletter/
  - title: Tips & Tricks
    url: /tips-and-tricks/
  - title: Webinars
    url: /webinars/
show_custom_links: true
client:
  name: Kenneth Kelly
  title:
  license_number:
  about_markdown: >-
    iPPi Ireland’s Independent Property Price Register has been developed in
    conjunction with UCD’s Analytics department and over 200 Agents, Valuers and
    Business owners across Ireland.


    iPPi uses elastic search to match and reference house transactions on the
    Property Price register with any historical reference to these properties
    online. iPPi brings a new level of understanding and context to the housing
    market in Ireland.
  brand: iPPi
  brokerage:
  market: Dublin
  address: >-
    NovaUCD, Belfield Innovation Park, University College Dublin<br>Dublin 4,
    Ireland
  phone: 00 353 1 497 7705
  phone_type:
  phone2:
  phone2_type:
  email: ippi@4property.com
  url: 'https://ippi.io'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.png
    CTA_title: Better Property Valuation in minutes
    CTA_text: >-
      iPPi, a new wave technology company in Dublin. iPPi is an all-one Property
      Analytics Data Platform that provides market intelligence and analytics to
      anyone connected to the property industry, Providing in-depth, micro, and
      macro analysis on the property market.
    CTA_link_text: Learn More
    CTA_url: 'https://www.4property.com/ippi/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/IPPiio-103206831152113'
  linkedin_url: 'https://www.linkedin.com/company/ippindex/'
  youtube_url: 'https://www.youtube.com/channel/UCnxHbg9I7pMkmZwNROOk_DQ'
  twitter_url: 'https://twitter.com/iPPindex'
  instagram_url: 'https://www.instagram.com/ippi.io/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: >-
    https://open.spotify.com/show/0F6I4KMTV9WDTgrSo03gsa?si=2ainiXm5Ti6Hw8jQPrLxEw
podcast:
  title: iPPi Insider
  categories:
    - Education
  image: /uploads/youtube-cover-2-1.png
  subtitle:
  description: >-
    iPPi Insider show explores Innovation in a number of sectors.


    In each episode, we learn to understand all things


    Marketing,

    Exploring Innovation,

    Technology

    Staying better informed in the digital transformation

    Having the ability to seek to understand more.

    Synergising with like-minded individuals and digitalizing at every step we
    can.


    New episodes brought to each Friday with a lot of interesting humans
    bringing you insights from their to day to day lives.
  keywords: >-
    Real Estate for sale,  Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Dublin, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer. valuers
  author: Kenneth Kelly
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Better Valuations in Minutes
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e91a6e'
  theme_color: '#131d3c'
  accent_color: '#e40c90'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#0c0d34'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#0c0d34'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'