audit_header: false
title: Technology Solutions for Property Professionals
description: Our mission at 4Property is to be your best resource for Dublin real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The 4Property, your professional Dublin Real Estate Agents.
show_custom_links_new_tab: false
custom_links:
  - title:
    url:
show_custom_links: true
custom_links:
  - title: Join iPPi
    url: https://ippi.4property.com/app/#/register
  - title: Events
    url: /events/
  - title: Monthly Newsletter
    url: /newsletter/
  - title: Tips & Tricks
    url: /tips-and-tricks/

client:
  name: Kenneth Kelly
  title:
  license_number:
  about_markdown: |
    iPPi Ireland’s Independent Property Price Register has been developed in conjunction with UCD’s Analytics department and over 200 Agents, Valuers and Business owners across Ireland.

    iPPi uses elastic search to match and reference house transactions on the Property Price register with any historical reference to these properties online. iPPi brings a new level of understanding and context to the housing market in Ireland.
  brand: iPPi
  brokerage:
  market: Dublin
  address: NovaUCD, Belfield Innovation Park, University College Dublin Dublin 4, Ireland
  phone: 00 353 1 497 7705
  phone_type:
  phone2:
  phone2_type:
  email: ippi@4property.com
  url: https://www.4property.com/iPPi

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.png
    CTA_title: "Property Appraisals, Valuations & Market Intelligence"
    CTA_text: "By matching & referencing house transactions on the Property Price register with any historical reference to these properties online iPPi brings a new level of understanding & context to the housing market in Ireland."
    CTA_link_text: "Learn More"
    CTA_url: https://www.4property.com/ippi/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Looking for a Dublin Home?"
#     CTA_text2: "Search the entire MLS for your Dublin home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/IPPiio-103206831152113
  linkedin_url: https://www.linkedin.com/company/ippindex/
  youtube_url: https://www.youtube.com/channel/UCnxHbg9I7pMkmZwNROOk_DQ
  twitter_url: https://twitter.com/4PropertyIE
  instagram_url: https://www.instagram.com/ippi.io/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Dublin Real Estate Podcast with Kenneth Kelly'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Dublin Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from 4Property - your professional Dublin Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Dublin, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kenneth Kelly'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Better Valuations in Minutes
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg

site_colors:
  brand_color: '#F51088'
  theme_color: '#0c0d34'
  accent_color: '#e40c90'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#0c0d34'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#0c0d34'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
